# ========================================
# 抢老师系统 - 统一配置文件
# ========================================

# 应用基础配置
spring:
  application:
    name: ${APP_NAME:grabTeacher-backend}
  # 激活的配置文件（通过环境变量控制）
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE:20MB}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE:20MB}

  # ========================================
  # 数据库配置
  # ========================================
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/grabteacher?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    # 数据库连接池配置
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:20}
      minimum-idle: ${DB_POOL_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}



  # ========================================
  # JPA/Hibernate 配置
  # ========================================
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
  
  # ========================================
  # 国际化配置
  # ========================================
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
  
  # ========================================
  # 静态资源配置
  # ========================================
  web:
    resources:
      add-mappings: ${WEB_RESOURCES_MAPPING:false}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:1}
      # 提高超时时间，避免高并发下偶发超时
      timeout: ${REDIS_TIMEOUT:10000ms}
      lettuce:
        pool:
          # 提升连接池容量以支撑并发
          max-active: ${REDIS_POOL_MAX_ACTIVE:100}
          max-idle: ${REDIS_POOL_MAX_IDLE:50}
          min-idle: ${REDIS_POOL_MIN_IDLE:10}
          # 等待可用连接的最大等待时长
          max-wait: ${REDIS_POOL_MAX_WAIT:10000ms}
        # 适当加大优雅关闭时间
        shutdown-timeout: ${REDIS_SHUTDOWN_TIMEOUT:200ms}

  # ========================================
  # 缓存配置
  # ========================================
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL:PT30M}
      cache-null-values: false
      use-key-prefix: true
      key-prefix: ${CACHE_KEY_PREFIX:grabTeacher:cache:}

# ========================================
# 服务器配置
# ========================================
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

  # ========================================
  # 错误处理配置
  # ========================================
  error:
    include-message: ${ERROR_INCLUDE_MESSAGE:never}
    include-stacktrace: ${ERROR_INCLUDE_STACKTRACE:never}
    include-binding-errors: ${ERROR_INCLUDE_BINDING_ERRORS:never}

# ========================================
# MyBatis Plus 配置
# ========================================
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.touhouqing.grabteacherbackend.model.entity
  configuration:
    map-underscore-to-camel-case: true
    # 关闭控制台 SQL 输出，降低噪音；如需调试可用环境变量 MYBATIS_LOG_IMPL 重启覆盖
    log-impl: ${MYBATIS_LOG_IMPL:}

# ========================================
# JWT 配置
# ========================================
jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}

# ========================================
# CORS 配置
# ========================================
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

# ========================================
# 日志配置
# ========================================
logging:
  level:
    com.touhouqing.grabteacherbackend: ${LOG_LEVEL_APP:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}

# ========================================
# 阿里云 OSS 配置
# ========================================
aliyun:
  oss:
    endpoint: ${ALIYUN_OSS_ENDPOINT:oss-cn-beijing.aliyuncs.com}
    accessKeyId: ${ALIYUN_OSS_AK:LTAI5tJzcSEY45izYsWscbz2}
    accessKeySecret: ${ALIYUN_OSS_SK:}
    bucket: ${ALIYUN_OSS_BUCKET:touhouqing}
    dirPrefix: ${ALIYUN_OSS_DIR_PREFIX:uploads/}
